language: python
python:
    - "2.7"
install: 
    - "pip install -r requirements.pip --use-mirrors"
env: "DJANGO_SETTINGS_MODULE=simp.settings"
script:
    - "cd simp"
    - "django-admin.py test -- --cov inventory"
