language: python
python:
    - "2.7"
install: 
    - "pip install -r requirements.pip --use-mirrors"
    - "python setup.py develop"
env: "DJANGO_SETTINGS_MODULE=simp.settings"
script:
    - "pwd"
    - "cd simp; pwd"
    - "cd simp; django-admin.py test -- --cov simp.inventory"
